source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "minima", "~> 2.5"
gem "jekyll-sitemap"
gem "webrick", "~> 1.9"

platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo-data"
  gem "wdm", "~> 0.2.0"
end
